/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gerenciadorcondominio.View;

import com.mycompany.gerenciadorcondominio.Controller.FaturaController;

/**
 *
 * @author Igor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProp = new javax.swing.JMenu();
        jMenuMor = new javax.swing.JMenu();
        jMenuRes = new javax.swing.JMenu();
        jMenuFat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuProp.setText("Proprietarios");
        jMenuProp.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuPropMenuSelected(evt);
            }
        });
        jMenuProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPropActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuProp);

        jMenuMor.setText("Moradores");
        jMenuMor.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuMorMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuMor);

        jMenuRes.setText("Residencias");
        jMenuRes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuResMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuRes);

        jMenuFat.setText("Faturas");
        jMenuFat.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuFatMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuFat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPropActionPerformed

    private void jMenuPropMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuPropMenuSelected
        // TODO add your handling code here:
        this.dispose();
        new ProprietariosView().setVisible(true);
    }//GEN-LAST:event_jMenuPropMenuSelected

    private void jMenuMorMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuMorMenuSelected
        // TODO add your handling code here:
        this.dispose();
        new MoradoresView().setVisible(true);
    }//GEN-LAST:event_jMenuMorMenuSelected

    private void jMenuResMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuResMenuSelected
        // TODO add your handling code here:
        this.dispose();
        new ResidenciaView().setVisible(true);
    }//GEN-LAST:event_jMenuResMenuSelected

    private void jMenuFatMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuFatMenuSelected
        // TODO add your handling code here:
        this.dispose();
        new FaturasView(FaturaController.getInstancia()).setVisible(true);
    }//GEN-LAST:event_jMenuFatMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFat;
    private javax.swing.JMenu jMenuMor;
    private javax.swing.JMenu jMenuProp;
    private javax.swing.JMenu jMenuRes;
    // End of variables declaration//GEN-END:variables
}
